# log
logging:
  config: classpath:logback-spring-prod.xml
  level:
    root: info
#rabbit

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wms.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#feignclient
feign:
  client:
    config:
      default:
        loggerLevel: basic
        connectTimeout: ${mfeign.http-timeout}
        readTimeout: ${mfeign.http-timeout}
        requestInterceptors:
          - eep.sippr.eepj.springboot.feign.interceptor.Oauth2TokenRelayRequestIntecepor
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

#spring
spring:
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #database
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${database.url}:${database.port:3306}/${database.name}?characterEncoding=utf-8&useSSL=false
      username: ${database.username}
      password: ${database.password}
      initial-size: ${database.initialSize:2}
      min-idle: ${database.minIdle:1}
      max-active: ${database.maxActive:20}
      max-wait: ${database.maxWait:60000}
      time-between-eviction-runs-millis: ${database.timeBetweenEvictionRunsMillis:60000}
      min-evictable-idle-time-millis: ${database.minEvictableIdleTimeMillis:300000}
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: ${database.testWhileIdle:true}
      test-on-borrow: ${database.testOnBorrow:false}
      test-on-return: ${database.testOnReturn:false}
      pool-prepared-statements: ${database.poolPreparedStatements:false}
      max-pool-prepared-statement-per-connection-size: ${database.maxPoolPreparedStatementPerConnectionSize:20}
      filters: stat,wall,config
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 111111
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
  #cloud
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-url}
        namespace: ${nacos.namespace}
        cluster-name: ${nacos.cluster-name}
        metadata:
          version: ${nacos.version}
          target-version: ${nacos.target-version}
  #sleuth-zipkin
  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    base-url: ${zipkin.base-url}
    discovery-client-enabled: false


#eepj-boot-framework
eepj:
  autoconfig:
    uid:
      generate:
        enabled: true
        uid-type: mongodb
    db:
      sqlexception:
        interceptor:
          enabled: true
          database-type: mysql
      mybatis:
        plugins:
          enabled: true
          database-type: mysql
    web:
      basic:
        mode-type: api
      cros:
        #正式发布时关闭
        enabled: true
        cors-urls: /web-api/**,/m-api/**,/open-api/**
      swagger:
        enabled: true
        title: 工作社交平台基础服务接口
    security:
      oauth2:
        resource:
          enabled: false
          authenticated-urls: /web-api/**,/m-api/**,/open-api/**
          public-key: ${authentication.public.key}
    cloud:
      enable-ribbon: true
    redis:
      enabled: true
      host: ${redis.host}
      port: ${redis.port}
      parser-package: siirisoft.wscp
# management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always